services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app/
     # - node_modules:/app/node_modules
    ports:
      - 8080:8080

  prod:
    build:
      context: .
    volumes:
      - node_modules:/app/node_modules
    ports:
      - 8080:8080

volumes:
  node_modules: